### ISSUE TITLE
Device Unable to connect to IOT Hub

### ISSUE THREAD

**Issue by abhayJava** [Azure-Samples/azure-iot-samples-java#7]
While connecting to azure iot hub using java sdk it throws exception mentioned at 

azure-iot-samples-java/iot-hub/Quickstarts/simulated-device-2/src/main/java/com/microsoft/docs/iothub/samples/SimulatedDevice.java
------------------------------------

### Minimal steps to reproduce
1. az login (In azure cli for windows)
2. Build the jar from project azure-iot-samples-java/iot-hub/Quickstarts/simulated-device-2
3. java -jar simulated-device-2-1.0.0-with-deps.jar
4. Throws exception

### Any log messages given by the failure
> Exception in thread "main" java.io.IOException: Unable to connect to serviceUnable to connect to server
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:139)
        at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttTransport.open(MqttTransport.java:83)
        at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:212)
        at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:198)
        at com.microsoft.docs.iothub.samples.SimulatedDevice.main(SimulatedDevice.java:157)

### Expected/desired behavior
>Device Should connect and start sending message

### OS and Version?
> Windows 10

[ClassWithCustomIOtHUbNameAndDeviceName.txt](https://github.com/Azure-Samples/azure-iot-samples-java/files/2652577/ClassWithCustomIOtHUbNameAndDeviceName.txt)

**Comment by jasmineymlo** [comment]
@abhayJava sorry for the late reply.  Did you replace    private static String connString = "{Your device connection string here}"; with your valid connection string??

**Comment by yzhong94** [comment]
@abhayJava here's a guide for troubleshooting connectivity: https://docs.microsoft.com/en-us/azure/iot-hub/tutorial-connectivity

**Comment by yzhong94** [comment]
Closing for now.  @abhayJava if you run into more issues, please go ahead and file the issues here https://github.com/Azure/azure-iot-sdk-java
